### ISSUE TITLE
Please publish surfman 0.9.2

### ISSUE THREAD

**Issue by Nopey** [servo/rust-offscreen-rendering-context#280]
Now that #275 is merged and brings rwh 0.6 support, I'd like to update servo webxr & servo/servo.

I don't think this should be released as 0.9.2 because #275 is a breaking change (the "sm-raw-window-handle" feature is now called "sm-raw-window-handle-05", for a start).

To do this without publishing surfman to crates.io, webxr and servo/servo would *both* have to specify the *same commit hash*, or frailly depend on the latest code on surfman's master branch (which will surely receive breaking changes)

Blocks:
- https://github.com/servo/webxr/pull/221
- https://github.com/servo/servo/pull/31278

Thank you!

**Comment by mrobinson** [comment]
surfman 0.9.2 has now been released: https://crates.io/crates/surfman/0.9.2
