### ISSUE TITLE
Workspace removal broke publishing

### ISSUE THREAD

**Issue by jdm** [servo/rust-offscreen-rendering-context#302]
There are several issues:
1. the workspace removal and subsequent restructuring broke a number of symlinks that are present in the android-example subdirectory (https://github.com/servo/surfman/tree/main/android-example/app/src/main/assets and https://github.com/servo/surfman/tree/main/android-example/app/src/main/jniLibs/arm64-v8a)
2. `cargo publish` attempts to verify that all files in android-example are actually present, so we can't publish without fixing the first issue
3. the changes in 1a522fac8519074177bddab32643ec6426b1e85f broke android-example compilation (incidentally, renaming a public module should have been a breaking change and caused 0.10.0)
4. android-example compilation is no longer verified in CI, so we didn't detect issue 3

**Comment by jdm** [comment]
I worked around this for 0.9.5 by fixing the assets symlinks, unlinking the missing .so, and running with --allow-dirty.

**Comment by jschwe** [comment]
Just a note - the android example [was already broken](https://github.com/servo/surfman/issues/200).
We definitely should add cargo semver checks to CI though.

**Comment by jschwe** [comment]
This was fixed by https://github.com/servo/surfman/pull/303, right?

**Comment by mrobinson** [comment]
Yes, I think so!
